### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by stuffi3000** [rafjaf/BetterJustel#1]
Dear rafjaf,

As a fellow Belgian jurist I would like to first of all thank you very much for this. We all know how Justel is in a huge need of a makeover, so this add on really changes the all around user experience for the better. Great work!

If you were to ever add support for Firefox, you'd make me very very happy.

Thanks again for this. I really feel like it needs more attention from the legal community.

**Comment by rafjaf** [comment]
Thanks for your feedback! I tried the other day to port it to Firefox, which is supposed to support Manifest v3 since recently. Concretely, that means that the extension written for Chrome should automatically be compatible with Firefox. Unfortunately, the implementation seems to be slightly different and when I tried it on Firefox (even after adapting the manifest.json file), the content script did not seem to work for reasons I could not understand. I will dig further, but any help would be most welcome!

**Comment by rafjaf** [comment]
@stuffi3000 I think I found a way around. The extension has now been sent for review to Firefox team and should be published shortly on https://addons.mozilla.org/fr/firefox/addon/better-justel/

Do not hesitate to signal any problem you may encounter with it.

IMPORTANCE NOTICE: If you are using the Firefox extension, the first time you will surf to Justel website, a blue dot will appear on the icon of the extension. You must right-click on the extension icon and grant it permission to always run on [www.ejustice.fgov.be](http://www.ejustice.fgov.be/). Otherwise, the extension will not work.

**Comment by stuffi3000** [comment]
> @stuffi3000 I think I found a way around. The extension has now been sent for review to Firefox team and should be published shortly on https://addons.mozilla.org/fr/firefox/addon/better-justel/
> 
> Do not hesitate to signal any problem you may encounter with it.
> 
> IMPORTANCE NOTICE: If you are using the Firefox extension, the first time you will surf to Justel website, a blue dot will appear on the icon of the extension. You must right-click on the extension icon and grant it permission to always run on [www.ejustice.fgov.be](http://www.ejustice.fgov.be/). Otherwise, the extension will not work.

Wow, that's what I would call efficient! Thanks again, the extension truly is a Godsent. I'll take a closer look at the Firefox version on Monday probably and get back to you if I run into any issues.
